-- Auto-generated by matugen — do not edit manually.
-- Usage: local colors = require("colors")
local M = {}

M.image = "{{image}}"

<* for name, value in colors *>
M.{{name}} = "rgba({{value.default.hex_stripped}}ff)"
<* endfor *>
return M
